// One-shot seed script.
//
// Usage:
//   dart run tool/seed_supabase.dart > seed.sql
//
// Paste the generated seed.sql into the Supabase SQL Editor to populate
// the `categories` and `questions` tables.
//
// The script reads from the in-app category list and outputs
// deterministic INSERT statements.

// ignore_for_file: avoid_print

import 'dart:io';

void main() {
  final sink = stdout;

  // ── Categories ─────────────────────────────────────────────────────────────
  final categories = [
    {'id': '1', 'name': 'Culture Générale', 'icon': '🧠', 'color_hex': '9C27B0', 'sort_order': 1},
    {'id': '2', 'name': 'Jeux Vidéo', 'icon': '🎮', 'color_hex': '2196F3', 'sort_order': 2},
    {'id': '3', 'name': 'Cinéma & Séries', 'icon': '🎬', 'color_hex': 'F44336', 'sort_order': 3},
    {'id': '4', 'name': 'Musique', 'icon': '🎵', 'color_hex': 'E91E63', 'sort_order': 4},
    {'id': '5', 'name': 'Géographie', 'icon': '🌍', 'color_hex': '4CAF50', 'sort_order': 5},
    {'id': '6', 'name': 'Littérature', 'icon': '📚', 'color_hex': 'FF9800', 'sort_order': 6},
    {'id': '7', 'name': 'Sciences', 'icon': '🔬', 'color_hex': '00BCD4', 'sort_order': 7},
    {'id': '8', 'name': 'Histoire', 'icon': '⏰', 'color_hex': 'FFC107', 'sort_order': 8},
    {'id': '9', 'name': 'Sport', 'icon': '⚽', 'color_hex': '009688', 'sort_order': 9},
  ];

  sink.writeln('-- ============================================================');
  sink.writeln('-- QuizzUp — Seed script (auto-generated by tool/seed_supabase.dart)');
  sink.writeln('-- Run once in Supabase SQL Editor');
  sink.writeln('-- ============================================================');
  sink.writeln();

  sink.writeln('-- Categories');
  sink.writeln('INSERT INTO categories (id, name, icon, color_hex, sort_order) VALUES');
  final catLines = categories.map((c) =>
    "  ('${c['id']}', \$\$${c['name']}\$\$, '${c['icon']}', '${c['color_hex']}', ${c['sort_order']})"
  ).toList();
  sink.writeln(catLines.join(',\n'));
  sink.writeln('ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon,');
  sink.writeln('  color_hex = EXCLUDED.color_hex, sort_order = EXCLUDED.sort_order;');
  sink.writeln();

  // ── Questions ──────────────────────────────────────────────────────────────
  sink.writeln('-- Questions');
  sink.writeln('INSERT INTO questions (id, category_id, question, answers, correct_answer_index, difficulty, explanation) VALUES');

  final questions = _allQuestions();
  final qLines = questions.map((q) {
    final answersJson = _toJsonArray(q['answers'] as List<String>);
    final explanation = q['explanation'] != null
        ? "\$\$${_escapeDollar(q['explanation'] as String)}\$\$"
        : 'NULL';
    return "  ('${q['id']}', '${q['categoryId']}', \$\$${_escapeDollar(q['question'] as String)}\$\$, '$answersJson'::jsonb, ${q['correctIndex']}, '${q['difficulty']}', $explanation)";
  }).toList();

  sink.writeln(qLines.join(',\n'));
  sink.writeln('ON CONFLICT (id) DO NOTHING;');
  sink.writeln();
  sink.writeln('-- Done! ${questions.length} questions inserted.');
}

String _toJsonArray(List<String> items) {
  final escaped = items.map((s) => '"${s.replaceAll('"', '\\"').replaceAll("'", "\\'")}"').join(',');
  return '[$escaped]';
}

String _escapeDollar(String s) => s.replaceAll(r'$', r'\$');

List<Map<String, dynamic>> _allQuestions() {
  return [
    // ── Culture Générale (1) ──
    _q('cg1', '1', 'Quelle est la capitale de la France ?', ['Lyon', 'Paris', 'Marseille', 'Toulouse'], 1),
    _q('cg2', '1', 'Combien de continents y a-t-il sur Terre ?', ['5', '6', '7', '8'], 2),
    _q('cg3', '1', 'Quel est le plus grand océan du monde ?', ['Atlantique', 'Pacifique', 'Indien', 'Arctique'], 1),
    _q('cg4', '1', 'Quelle est la planète la plus proche du Soleil ?', ['Vénus', 'Mercure', 'Terre', 'Mars'], 1),
    _q('cg5', '1', 'Combien de jours y a-t-il dans une année bissextile ?', ['364', '365', '366', '367'], 2),
    _q('cg6', '1', "Quel est le symbole chimique de l'or ?", ['Au', 'Ag', 'Fe', 'Cu'], 0),
    _q('cg7', '1', 'Quelle est la langue la plus parlée au monde ?', ['Anglais', 'Espagnol', 'Mandarin', 'Français'], 2),
    _q('cg8', '1', 'Quel est le plus grand désert du monde ?', ['Sahara', 'Gobi', 'Antarctique', 'Arctique'], 2),
    _q('cg9', '1', 'Combien de côtés a un hexagone ?', ['4', '5', '6', '7'], 2),
    _q('cg10', '1', 'Quel est le plus grand mammifère du monde ?', ['Éléphant', 'Girafe', 'Baleine bleue', 'Rhinocéros'], 2),
    _q('cg11', '1', 'Quelle est la vitesse de la lumière ?', ['300 000 km/s', '150 000 km/s', '450 000 km/s', '200 000 km/s'], 0),
    _q('cg12', '1', 'Quel est le plus grand pays du monde ?', ['Canada', 'Chine', 'Russie', 'États-Unis'], 2),
    _q('cg13', '1', "Combien de lettres compte l'alphabet français ?", ['24', '25', '26', '27'], 2),
    _q('cg14', '1', 'Quel est le plus haut sommet du monde ?', ['K2', 'Mont Everest', 'Kilimandjaro', 'Mont Blanc'], 1),
    _q('cg15', '1', 'Quelle est la monnaie du Japon ?', ['Yuan', 'Yen', 'Won', 'Ringgit'], 1),
    _q('cg16', '1', "Combien de minutes y a-t-il dans une heure ?", ['50', '60', '70', '100'], 1),
    _q('cg17', '1', 'Quel est le plus grand lac du monde ?', ['Caspienne', 'Supérieur', 'Victoria', 'Baïkal'], 0),
    _q('cg18', '1', "Quelle est la capitale de l'Australie ?", ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'], 2),
    _q('cg19', '1', 'Combien de doigts a une main ?', ['4', '5', '6', '7'], 1),
    _q('cg20', '1', "Quel est le symbole chimique de l'eau ?", ['H2O', 'CO2', 'O2', 'NaCl'], 0),
    _q('cg21', '1', 'Quelle est la plus grande île du monde ?', ['Madagascar', 'Groenland', 'Borneo', 'Nouvelle-Guinée'], 1),
    _q('cg22', '1', "Combien de saisons y a-t-il dans une année ?", ['2', '3', '4', '5'], 2),
    _q('cg23', '1', 'Quel est le plus petit pays du monde ?', ['Monaco', 'Vatican', 'Nauru', 'San Marino'], 1),
    _q('cg24', '1', 'Quelle est la capitale du Brésil ?', ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador'], 2),
    _q('cg25', '1', "Combien de planètes y a-t-il dans notre système solaire ?", ['7', '8', '9', '10'], 1),
    // ── Jeux Vidéo (2) ──
    _q('jv1', '2', "Quel jeu vidéo a vendu le plus d'exemplaires ?", ['GTA V', 'Minecraft', 'Tetris', 'Fortnite'], 1),
    _q('jv2', '2', 'Quelle est la première console de jeu vidéo ?', ['Atari 2600', 'Magnavox Odyssey', 'NES', 'PlayStation'], 1),
    _q('jv3', '2', 'Dans quel jeu trouve-t-on le personnage Link ?', ['Final Fantasy', 'The Legend of Zelda', 'Super Mario', 'Pokémon'], 1),
    _q('jv4', '2', 'Quel est le créateur de Minecraft ?', ['Markus Persson', 'Shigeru Miyamoto', 'Hideo Kojima', 'Gabe Newell'], 0),
    _q('jv5', '2', 'Quelle entreprise a créé "The Elder Scrolls" ?', ['Blizzard', 'Bethesda', 'Ubisoft', 'EA'], 1),
    _q('jv6', '2', 'Dans quel jeu peut-on trouver Master Chief ?', ['Call of Duty', 'Halo', 'Gears of War', 'Destiny'], 1),
    _q('jv7', '2', 'Quel est le nom du protagoniste de "The Witcher 3" ?', ['Geralt de Riv', 'Ciri', 'Yennefer', 'Triss'], 0),
    _q('jv8', '2', 'Quelle est la première console portable de Nintendo ?', ['Game Boy', 'Nintendo DS', 'Game & Watch', 'Switch'], 2),
    _q('jv9', '2', 'Quel studio a développé "The Last of Us" ?', ['Naughty Dog', 'Rockstar', 'CD Projekt Red', 'Insomniac'], 0),
    _q('jv10', '2', "Quel est le personnage principal de \"Assassin's Creed\" ?", ['Ezio', 'Altair', 'Connor', 'Edward'], 1),
    _q('jv11', '2', 'Dans quel jeu peut-on construire des villes ?', ['SimCity', 'Cities: Skylines', 'Tropico', 'Tous les précédents'], 3),
    _q('jv12', '2', 'Quel est le nom du héros de "Final Fantasy VII" ?', ['Cloud', 'Squall', 'Tidus', 'Noctis'], 0),
    _q('jv13', '2', 'Quelle console a été créée par Sega ?', ['PlayStation', 'Xbox', 'Nintendo', 'Dreamcast'], 3),
    _q('jv14', '2', 'Quel est le jeu le plus vendu sur PlayStation 4 ?', ['God of War', 'Spider-Man', 'The Last of Us Part II', 'Horizon Zero Dawn'], 2),
    _q('jv15', '2', 'Dans quel jeu peut-on capturer des Pokémon ?', ['Digimon', 'Pokémon', 'Yu-Gi-Oh!', 'Beyblade'], 1),
    _q('jv16', '2', 'Quel est le créateur de "Super Mario" ?', ['Hideo Kojima', 'Shigeru Miyamoto', 'Sid Meier', 'Will Wright'], 1),
    _q('jv17', '2', 'Quel est le nom du protagoniste de "Tomb Raider" ?', ['Lara Croft', 'Nathan Drake', 'Indiana Jones', 'Elena Fisher'], 0),
    _q('jv18', '2', 'Quelle est la première version de "FIFA" ?', ['FIFA 94', 'FIFA 95', 'FIFA 96', 'FIFA 97'], 0),
    _q('jv19', '2', 'Dans quel jeu peut-on construire avec des blocs ?', ['Roblox', 'Minecraft', 'Terraria', 'Tous les précédents'], 3),
    _q('jv20', '2', 'Quel est le nom du héros de "Uncharted" ?', ['Lara Croft', 'Nathan Drake', 'Joel', 'Kratos'], 1),
    _q('jv21', '2', 'Quelle entreprise a créé "Call of Duty" ?', ['EA', 'Ubisoft', 'Activision', 'Bethesda'], 2),
    _q('jv22', '2', 'Quel est le jeu le plus joué au monde en 2023 ?', ['Minecraft', 'Fortnite', 'League of Legends', 'PUBG'], 0),
    _q('jv23', '2', 'Dans quel jeu peut-on trouver Pikachu ?', ['Digimon', 'Pokémon', 'Yu-Gi-Oh!', 'Beyblade'], 1),
    _q('jv24', '2', 'Quel est le nom du protagoniste de "Red Dead Redemption" ?', ['John Marston', 'Arthur Morgan', 'Dutch', 'Micah'], 1),
    _q('jv25', '2', 'Quelle console a été créée par Microsoft ?', ['PlayStation', 'Xbox', 'Nintendo', 'Sega'], 1),
  ];
}

Map<String, dynamic> _q(
  String id,
  String categoryId,
  String question,
  List<String> answers,
  int correctIndex, {
  String difficulty = 'medium',
  String? explanation,
}) {
  return {
    'id': id,
    'categoryId': categoryId,
    'question': question,
    'answers': answers,
    'correctIndex': correctIndex,
    'difficulty': difficulty,
    'explanation': explanation,
  };
}
